### ISSUE TITLE
I am not able to install required packages

### ISSUE THREAD

**Issue by josenimo** [TencentAILabHealthcare/scpDeconv#1]
Hello, 

I am trying to run scpDeconv, and I am not able to install the right packages in a conda environment, could you help me?

I have tried 
```
conda install python=3.6.8 scipy=1.5.4 torch=1.8.1 numpy=1.19.2 pandas=1.1.5 scanpy=1.7.2 scikit_learn=0.24.2

PackagesNotFoundError: The following packages are not available from current channels:

  - scikit_learn=0.24.2
  - scipy=1.5.4
  - torch=1.8.1

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
```

**Comment by Avon0905** [comment]
Hi, Jose,

Sorry for the late reply. This could be due to the package version, but any up-to-date package version can be utilized here. Furthermore, for the convenience of users, we have containerized our running environment using Docker and uploaded it to Docker-Hub. Please refer to the installation instructions in the readme file to install and run Docker, followed by executing scpDeconv within the container. 

Hope this solution will address your issue.

**Comment by josenimo** [comment]
Hey @Avon0905,

thank you for your response, and for creating the docker image.

I am trying to run scpdeconv on the demo dataset, but I am struggling to follow instructions.

Do I run the docker container, and inside the container run main.py? 
I cloned the github with the data folder, but I also cannot find the demo data inside Docker.

Could you post a more specific step by step instructions, I am sorry I have little experience with Docker.

**Comment by Avon0905** [comment]
Hi Jose,

Thank you for giving our tool a try! Just so you know, to run main.py with all the necessary dependencies, it's best to do so directly within the docker container. 

We've also combined Installation and Usage instructions into four easy steps for your convenience when trying out our demo.

The demo data is located in the folder 'data/murine_cellline', which can be found after cloning the Github repository.

We hope these updated instructions will help resolve your issue.

**Comment by josenimo** [comment]
Hi @Avon0905,

I am sorry, I am still not able to run the demo files. I will explain what I am doing, and you can tell me what I am doing wrong.

1. I install the docker container with `docker pull avonwang/scpdeconv:latest`
2. I run the docker container `docker run --name scpdeconv --gpus all -it --rm avonwang/scpdeconv:latest /bin/bash` 
3. In another terminal, I download the repository with `git clone https://github.com/TencentAILabHealthcare/scpDeconv.git`
4. Inside the docker container I try to command `cd scpDeconv/` it says there is no such file or directory
5. Inside the docker container I also cannot run `python3 main.py --dataset murine_cellline` because it cannot find the file or directory. 

Am I supposed to run the docker on the github repository? I am looking online and I can't find an example of how to do this

**Comment by Avon0905** [comment]
Hi Jose,

Sorry for the confusion. Acutually, step 3 - downloading the repository - should be completed inside the docker container, to ensure that you can find the `scpDeconv/` folder within the docker container. 

And I have revised your step accordingly:

1. Install the docker container with `docker pull avonwang/scpdeconv:latest`
2. Run the docker container `docker run --name scpdeconv --gpus all -it --rm avonwang/scpdeconv:latest /bin/bash`
3. Inside the docker container, download the repository with `git clone https://github.com/TencentAILabHealthcare/scpDeconv.git`
4. Inside the docker container, run the command `cd scpDeconv/ `
5. Inside the docker container, run `python3 main.py --dataset murine_cellline`
6. The result folder is still within the docker container, and you can find it by running `cd Result/murine_cellline/` inside the docker container.

Hope now you can successfully try our tool, and thank you again for promoting the convenience of our instructions.

**Comment by josenimo** [comment]
Hi @Avon0905,

This makes so much sense, I am sorry I never considered cloning a github repo inside the docker container. 
These instructions helped me very well, thank you!
